baseURL = "https://digili.no/"
languageCode = "en-us"
title = "Digili AS"
DefaultContentLanguage = "no"
theme = "ananke"

[params]
  custom_css = ["css/main.css"]
  site_logo = "/images/digili_logo.svg"

# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name = "Om oss"
#     url = "/about"
#   [[menu.main]]
#     identifier = "projects"
#     name = "Prosjekter"
#     url = "/projects"
#   [[menu.main]]
#     identifier = "news"
#     name = "Nyheter"
#     url = "/news"

[languages]
  [languages.no]
    contentDir = "content/no"
    weight = 1

  [languages.en]
    contentDir = "content/en"
    weight = 2
